DROP DATABASE IF EXISTS sessionstore;
DROP DATABASE IF EXISTS treasurehunt;
DROP DATABASE IF EXISTS instructortip;
DROP DATABASE IF EXISTS pacingguide;
DROP DATABASE IF EXISTS welcomeletter;
SOURCE /sql/schema_sessionstore.sql;
SOURCE /sql/schema_instructortips.sql;
SOURCE /sql/loadadmindata.sql;
SOURCE /sql/schema_treasurehunt.sql;
SOURCE /sql/schema_pacingguide.sql;
SOURCE /sql/pgviewerdata.sql;
SOURCE /sql/welcomeletterdata.sql;